version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
